server:
  port: 8080

spring:
  datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/spring
        username: root
        password: mysql
  data:
    jpa:
      repositories:
              enabled: true